// -----------------------------------------------------------------------------
// TRACK DATA — READ THIS BEFORE FILLING IN videoId
// -----------------------------------------------------------------------------
// Your brief says: "only include songs I have the right to use, or that stream
// from the rights holder's own YouTube upload with embedding enabled. Do not
// suggest, search for or add copyrighted tracks on my behalf."
//
// The 110 titles below are commercial Bollywood recordings (credited on your
// reference image to Himesh Reshammiya) — they're under active copyright,
// typically held by labels like T-Series/Zee Music/Sony Music. I have not
// searched YouTube for them and have not filled in any videoId, artist,
// film, or year, because doing so on your behalf is exactly what you asked
// me not to do, and I'd otherwise be guessing at metadata I can't verify.
//
// To finish this file:
//   1. For each track, find the SONG's official upload on the rights
//      holder's own YouTube channel (not a fan reupload, lyric video, or
//      "audio jukebox" from an unrelated channel).
//   2. Confirm embedding is enabled (if the video only offers a "Watch on
//      YouTube" link when embedded elsewhere, it's blocked — pick another
//      official source or drop the track).
//   3. Paste the 11-character video ID into `videoId`, and fill in
//      `artist` / `film` / `year` / `duration` from that same video's page.
//   4. Adding a song from here on is a one-line edit, per your brief.
//
// Every entry currently has an empty videoId, which means `useYouTubePlayer`
// will skip it via the same onError path used for tracks that get pulled
// post-launch (see hooks/useYouTubePlayer.ts) — so the scaffold runs, but
// plays nothing, until you populate real, rights-cleared IDs.
// -----------------------------------------------------------------------------

import type { Playlist } from "./youtube-types";

export const playlists: Playlist[] = [
  {
    id: "classic-favorites",
    name: "Classic & Favorites",
    tracks: [
      {
        id: "t001",
        title: "Aashiq Banaya Aapne",
        artist: "Himesh Reshammiya, Shreya Ghoshal",
        film: "Aashiq Banaya Aapne",
        year: 2005,
        duration: 364,
        videoId: "RlbGLrMuZ5I",
      },
      {
        id: "t002",
        title: "Aap Ki Kashish",
        artist: "Himesh Reshammiya, Ahir, Krishna",
        film: "Aashiq Banaya Aapne",
        year: 2005,
        duration: 335,
        videoId: "hIDmrWqFg_k",
      },
      {
        id: "t003",
        title: "Jhalak Dikhla Ja",
        artist: "Himesh Reshammiya",
        film: "Akshar",
        year: 2006,
        duration: 310,
        videoId: "vnlk8V-q0oU",
      },
      {
        id: "t004",
        title: "Tera Mera Milna",
        artist: "Himesh Reshammiya, Shreya Ghoshal",
        film: "Aap Kaa Surroor",
        year: 2007,
        duration: 295,
        videoId: "vJQvXHnkcIo",
      },
      {
        id: "t005",
        title: "Tera Surroor",
        artist: "Himesh Reshammiya",
        film: "Aap Kaa Surroor",
        year: 2007,
        duration: 350,
        videoId: "idNyQkZU2VA",
      },
      {
        id: "t006",
        title: "Naam Hai Tera",
        artist: "Himesh Reshammiya",
        film: "Aap Kaa Surroor (Album)",
        year: 2006,
        duration: 280,
        videoId: "v9rEc-yaI8I",
      },
      {
        id: "t007",
        title: "Mujhko Yaad Sataye Teri",
        artist: "Himesh Reshammiya",
        film: "Phir Hera Pheri",
        year: 2006,
        duration: 290,
        videoId: "nb0y9zx8yRE",
      },
      {
        id: "t008",
        title: "Jhoom Jhoom",
        artist: "Himesh Reshammiya",
        film: "Tom Dick And Harry",
        year: 2006,
        duration: 305,
        videoId: "TMiHf8b4fCA",
      },
      {
        id: "t009",
        title: "Aap Ki Khatir",
        artist: "Himesh Reshammiya",
        film: "Aap Ki Khatir",
        year: 2006,
        duration: 275,
        videoId: "W_BlwLWJ1NE",
      },
      {
        id: "t010",
        title: "Aashiqui Mein Teri",
        artist: "Himesh Reshammiya, Sunidhi Chauhan",
        film: "36 China Town",
        year: 2006,
        duration: 298,
        videoId: "pYiYSt5pGoU",
      },
      {
        id: "t011",
        title: "Zara Jhoom Jhoom",
        artist: "Himesh Reshammiya",
        film: "Tom Dick And Harry",
        year: 2006,
        duration: 312,
        videoId: "TMiHf8b4fCA",
      },
      {
        id: "t012",
        title: "Tanhaiyaan",
        artist: "Himesh Reshammiya, Sunidhi Chauhan",
        film: "Aap Kaa Surroor",
        year: 2007,
        duration: 320,
        videoId: "_j3wpZqZs9M",
      },
      {
        id: "t013",
        title: "Teri Yaad",
        artist: "Himesh Reshammiya, Badshah",
        film: "Teraa Surroor",
        year: 2016,
        duration: 265,
        videoId: "O_91EGrqP28",
      },
      {
        id: "t014",
        title: "Gustakh Dil Tere Liye",
        artist: "Himesh Reshammiya",
        film: "Dil Diya Hai",
        year: 2006,
        duration: 310,
        videoId: "AMU_v2badYY",
      },
      {
        id: "t015",
        title: "Dard Dilo Ke",
        artist: "Mohammed Irfan, Himesh Reshammiya",
        film: "The Xpose",
        year: 2014,
        duration: 302,
        videoId: "X57eHseHc1M",
      },
      {
        id: "t016",
        title: "Main Jahaan Rahoon",
        artist: "Rahat Fateh Ali Khan, Himesh Reshammiya",
        film: "Namastey London",
        year: 2007,
        duration: 388,
        videoId: "ZQlH0D_GPiE",
      },
      {
        id: "t017",
        title: "Viraaniyan",
        artist: "Himesh Reshammiya",
        film: "Namastey London",
        year: 2007,
        duration: 330,
        videoId: "VV9jThY8fzg",
      },
      {
        id: "t018",
        title: "Aanan Faanan",
        artist: "Jayesh Gandhi, Akriti Kakar, Himesh Reshammiya",
        film: "Namastey London",
        year: 2007,
        duration: 315,
        videoId: "oLGy6X3_ZpI",
      },
      {
        id: "t019",
        title: "Bichdann",
        artist: "Rahat Fateh Ali Khan, Himesh Reshammiya",
        film: "Son of Sardaar",
        year: 2012,
        duration: 300,
        videoId: "V8b0Em7Eo3s",
      },
      {
        id: "t020",
        title: "Dil Mera Todo Na",
        artist: "Himesh Reshammiya",
        film: "Aap Kaa Surroor",
        year: 2007,
        duration: 280,
        videoId: "2e08_N2c7b8",
      },
      {
        id: "t021",
        title: "Aafreen",
        artist: "Himesh Reshammiya, Harshdeep Kaur",
        film: "Aap Kaa Surroor",
        year: 2007,
        duration: 310,
        videoId: "K-j3k-W2K7c",
      },
      {
        id: "t022",
        title: "Odh Li Chunariya Tere Naam Ki",
        artist: "Kumar Sanu, Alka Yagnik, Himesh Reshammiya",
        film: "Pyaar Kiya To Darna Kya",
        year: 1998,
        duration: 375,
        videoId: "qEa4aGq0nuU",
      },
      {
        id: "t023",
        title: "Tere Naam",
        artist: "Udit Narayan, Alka Yagnik, Himesh Reshammiya",
        film: "Tere Naam",
        year: 2003,
        duration: 392,
        videoId: "tDCZLB5A-nc",
      },
      {
        id: "t024",
        title: "Tumse Milna",
        artist: "Udit Narayan, Alka Yagnik, Himesh Reshammiya",
        film: "Tere Naam",
        year: 2003,
        duration: 285,
        videoId: "3Y9zjI9oWaY",
      },
      {
        id: "t025",
        title: "Kyun Kisi Ko",
        artist: "Udit Narayan, Himesh Reshammiya",
        film: "Tere Naam",
        year: 2003,
        duration: 325,
        videoId: "iCZfjggJg3M",
      },
      {
        id: "t026",
        title: "O Jaana",
        artist: "Udit Narayan, Alka Yagnik, Kamaal Khan, KK, Shaan, Himesh Reshammiya",
        film: "Tere Naam",
        year: 2003,
        duration: 335,
        videoId: "0pehqPZuB8A",
      },
      {
        id: "t027",
        title: "O Meri Zohrajabeen",
        artist: "Himesh Reshammiya",
        film: "Phir Hera Pheri",
        year: 2006,
        duration: 290,
        videoId: "EH9yR6T4ePI",
      },
      {
        id: "t028",
        title: "Dil Ke Badle Sanam",
        artist: "Udit Narayan, Alka Yagnik, Himesh Reshammiya",
        film: "Kyon Ki",
        year: 2005,
        duration: 310,
        videoId: "fvwyPGBOEgY",
      },
      {
        id: "t029",
        title: "Kyon Ki Itna Pyar",
        artist: "Udit Narayan, Alka Yagnik, Himesh Reshammiya",
        film: "Kyon Ki",
        year: 2005,
        duration: 348,
        videoId: "vnCIjfkPooo",
      },
      {
        id: "t030",
        title: "Lagi Lagi",
        artist: "Himesh Reshammiya, Sunidhi Chauhan",
        film: "Aap Kaa Surroor",
        year: 2007,
        duration: 295,
        videoId: "Cw0Ne7EQcWI",
      },
      {
        id: "t031",
        title: "Teri Meri Love Story",
        artist: "Himesh Reshammiya",
        film: "Aap Kaa Surroor",
        year: 2007,
        duration: 300,
        videoId: "TeXOJZ7VyrU",
      },
      {
        id: "t032",
        title: "Aap Kaa Surroor",
        artist: "Himesh Reshammiya",
        film: "Aap Kaa Surroor",
        year: 2006,
        duration: 340,
        videoId: "idNyQkZU2VA",
      },
      {
        id: "t033",
        title: "Aap Kaa Surroor (Remix)",
        artist: "Himesh Reshammiya",
        film: "Aap Kaa Surroor",
        year: 2006,
        duration: 260,
        videoId: "Oqe_2fs5RIQ",
      },
      {
        id: "t034",
        title: "Dilnashin Dilnashin",
        artist: "K.K., Himesh Reshammiya",
        film: "Aashiq Banaya Aapne",
        year: 2005,
        duration: 305,
        videoId: "c8TqlaLU7gg",
      },
      {
        id: "t035",
        title: "Dillagi Mein Jo Beet Jaaye",
        artist: "Himesh Reshammiya, Shaan, Jayesh Gandhi, Vasundhara Das",
        film: "Aashiq Banaya Aapne",
        year: 2005,
        duration: 290,
        videoId: "fc0VL7mGs5g",
      },
      {
        id: "t036",
        title: "Tere Dil Ka Rishta",
        artist: "Himesh Reshammiya",
        film: "Koi Aap Sa",
        year: 2005,
        duration: 315,
        videoId: "g848L-hn4ns",
      },
      {
        id: "t037",
        title: "Kabhi Na Sukoon",
        artist: "Udit Narayan, Alka Yagnik, Himesh Reshammiya",
        film: "Koi Aap Sa",
        year: 2005,
        duration: 330,
        videoId: "UzlVX_xjwaQ",
      },
      {
        id: "t038",
        title: "Dil Keh Raha Hai",
        artist: "Kunal Ganjawala, Himesh Reshammiya",
        film: "Kyon Ki",
        year: 2005,
        duration: 322,
        videoId: "ekBCpIDZR4I",
      },
      {
        id: "t039",
        title: "Loot Jayenge",
        artist: "Himesh Reshammiya, Harshdeep Kaur",
        film: "Aap Ki Khatir",
        year: 2006,
        duration: 285,
        videoId: "TBQNPQs720A",
      },
      {
        id: "t040",
        title: "Soniye",
        artist: "K.K., Sunidhi Chauhan, Himesh Reshammiya",
        film: "Aap Ki Khatir",
        year: 2006,
        duration: 270,
        videoId: "PKSM4e0rrAc",
      },
      {
        id: "t041",
        title: "Tum Saanson Mein",
        artist: "Himesh Reshammiya, Tulsi Kumar",
        film: "Humko Deewana Kar Gaye",
        year: 2006,
        duration: 310,
        videoId: "w9Z8Z-DzXfM",
      },
      {
        id: "t042",
        title: "Tanha Jiya Na Jaaye",
        artist: "Himesh Reshammiya",
        film: "Tom Dick And Harry",
        year: 2006,
        duration: 290,
        videoId: "NJD5oPvlsCw",
      },
      {
        id: "t043",
        title: "Dil Vich Lagya",
        artist: "Himesh Reshammiya, Sonu Nigam, Akriti Kakar",
        film: "Chup Chup Ke",
        year: 2006,
        duration: 305,
        videoId: "FWO9pbfdvD0",
      },
      {
        id: "t044",
        title: "Ishq Ne Tere",
        artist: "Himesh Reshammiya, Jayesh Gandhi",
        film: "Ahista Ahista",
        year: 2006,
        duration: 280,
        videoId: "CzNsnAQwN74",
      },
      {
        id: "t045",
        title: "Shabe Firaq",
        artist: "Himesh Reshammiya, Tulsi Kumar",
        film: "Chup Chup Ke",
        year: 2006,
        duration: 275,
        videoId: "XvRKx81O_9E",
      },
      {
        id: "t046",
        title: "Laagi Chhute Na",
        artist: "Himesh Reshammiya",
        film: "Aap Kaa Surroor",
        year: 2007,
        duration: 315,
        videoId: "RlbGLrMuZ5I",
      },
      {
        id: "t047",
        title: "Dil Diya",
        artist: "Himesh Reshammiya, Himani Kapoor",
        film: "Dil Diya Hai",
        year: 2006,
        duration: 295,
        videoId: "wb6px2F5o_Y",
      },
      {
        id: "t048",
        title: "Tere Layee",
        artist: "Himesh Reshammiya, Tulsi Kumar",
        film: "Fool N Final",
        year: 2007,
        duration: 285,
        videoId: "r3xs4YRSMiE",
      },
      {
        id: "t049",
        title: "Yeh Dooriyaan",
        artist: "Himesh Reshammiya",
        film: "Fool N Final",
        year: 2007,
        duration: 310,
        videoId: "Ep09LLwmvMw",
      },
      {
        id: "t050",
        title: "Jhoot Nahin Bolna",
        artist: "Himesh Reshammiya, Shreya Ghoshal",
        film: "Aap Kaa Surroor",
        year: 2007,
        duration: 300,
        videoId: "3Y9zjI9oWaY",
      },
      {
        id: "t051",
        title: "Ya Ali",
        artist: "Zubeen Garg, Himesh Reshammiya",
        film: "Gangster",
        year: 2006,
        duration: 295,
        videoId: "pmHnlBqjpm0",
      },
      {
        id: "t052",
        title: "Apne",
        artist: "Sonu Nigam, Jaspinder Narula, Jayesh Gandhi, Himesh Reshammiya",
        film: "Apne",
        year: 2007,
        duration: 330,
        videoId: "Kwqljnl_ccY",
      },
      {
        id: "t053",
        title: "Ankh Vich Chehra Pyar Da",
        artist: "Himesh Reshammiya, Shreya Ghoshal",
        film: "Apne",
        year: 2007,
        duration: 290,
        videoId: "YYUu9s37W-0",
      },
      {
        id: "t054",
        title: "Soniye Je Tere",
        artist: "Sonu Nigam, Jayesh Gandhi, Himesh Reshammiya",
        film: "Karzzzz",
        year: 2008,
        duration: 315,
        videoId: "qyYktDnI9PI",
      },
      {
        id: "t055",
        title: "Ek Haseena Thi",
        artist: "Himesh Reshammiya, Shreya Ghoshal",
        film: "Karzzzz",
        year: 2008,
        duration: 340,
        videoId: "47Tsuz5OhBU",
      },
      {
        id: "t056",
        title: "Zindagi Jaise Ek Radio",
        artist: "Himesh Reshammiya",
        film: "Radio",
        year: 2009,
        duration: 285,
        videoId: "AWVeDzfO_K8",
      },
      {
        id: "t057",
        title: "Kajra Kajra Kajraare",
        artist: "Himesh Reshammiya, Sunidhi Chauhan",
        film: "Kajraare",
        year: 2010,
        duration: 300,
        videoId: "k_rWvSracr4",
      },
      {
        id: "t058",
        title: "Milenge Milenge",
        artist: "Alka Yagnik, Jayesh Gandhi, Himesh Reshammiya",
        film: "Milenge Milenge",
        year: 2010,
        duration: 295,
        videoId: "Q9SSbcxijYk",
      },
      {
        id: "t059",
        title: "Desi Beat",
        artist: "Mika Singh, Amrita Kak, Himesh Reshammiya",
        film: "Bodyguard",
        year: 2011,
        duration: 250,
        videoId: "lFjwkZS2GCo",
      },
      {
        id: "t060",
        title: "Teri Meri",
        artist: "Rahat Fateh Ali Khan, Shreya Ghoshal, Himesh Reshammiya",
        film: "Bodyguard",
        year: 2011,
        duration: 325,
        videoId: "WZQLKr0Mb8Y",
      },
      {
        id: "t061",
        title: "Tu Hi Rab Tu Hi Dua",
        artist: "Rahat Fateh Ali Khan, Tulsi Kumar, Himesh Reshammiya",
        film: "Dangerous Ishhq",
        year: 2012,
        duration: 310,
        videoId: "ThhbP_kHBWc",
      },
      {
        id: "t062",
        title: "Chalao Na Naino Se",
        artist: "Mika Singh, Shreya Ghoshal, Himesh Reshammiya",
        film: "Bol Bachchan",
        year: 2012,
        duration: 305,
        videoId: "aJyTmT17Npg",
      },
      {
        id: "t063",
        title: "Rani Tu Mein Raja",
        artist: "Mika Singh, Bhavya Pandit, Yo Yo Honey Singh, Himesh Reshammiya",
        film: "Son of Sardaar",
        year: 2012,
        duration: 290,
        videoId: "kh-mxJAxXJI",
      },
      {
        id: "t064",
        title: "Main Deewana",
        artist: "Ganesh Hegde, Himesh Reshammiya",
        film: "Aap Kaa Surroor",
        year: 2007,
        duration: 275,
        videoId: "fc0VL7mGs5g",
      },
      {
        id: "t065",
        title: "Jumme Ki Raat",
        artist: "Mika Singh, Palak Muchhal, Himesh Reshammiya",
        film: "Kick",
        year: 2014,
        duration: 274,
        videoId: "dv_Qjzca56k",
      },
      {
        id: "t066",
        title: "Baaton Ko Teri",
        artist: "Arijit Singh, Himesh Reshammiya",
        film: "All Is Well",
        year: 2015,
        duration: 280,
        videoId: "c19t5ORk8Xo",
      },
      {
        id: "t067",
        title: "Prem Ratan Dhan Payo",
        artist: "Palak Muchhal, Himesh Reshammiya",
        film: "Prem Ratan Dhan Payo",
        year: 2015,
        duration: 319,
        videoId: "bPk9bSvQQoc",
      },
      {
        id: "t068",
        title: "Main Woh Chaand",
        artist: "Darshan Raval, Himesh Reshammiya",
        film: "Teraa Surroor",
        year: 2016,
        duration: 320,
        videoId: "8hBQJH2pHQ0",
      },
      {
        id: "t069",
        title: "Bekhudi",
        artist: "Darshan Raval, Aditi Singh Sharma, Himesh Reshammiya",
        film: "Teraa Surroor",
        year: 2016,
        duration: 345,
        videoId: "SfEk5W3zH98",
      },
      {
        id: "t070",
        title: "Sanam Teri Kasam",
        artist: "Ankit Tiwari, Palak Muchhal, Himesh Reshammiya",
        film: "Sanam Teri Kasam",
        year: 2016,
        duration: 314,
        videoId: "3N-ShXh6FOI",
      },
      {
        id: "t071",
        title: "Tera Chehra",
        artist: "Arijit Singh, Himesh Reshammiya",
        film: "Sanam Teri Kasam",
        year: 2016,
        duration: 274,
        videoId: "i6fuIGIzaAs",
      },
      {
        id: "t072",
        title: "Samjho Na",
        artist: "Aditya Narayan, Himesh Reshammiya",
        film: "Aap Kaa Surroor",
        year: 2006,
        duration: 285,
        videoId: "DrwU9OgJjW8",
      },
      {
        id: "t073",
        title: "Naiyo Lagda",
        artist: "Kamaal Khan, Palak Muchhal, Himesh Reshammiya",
        film: "Kisi Ka Bhai Kisi Ki Jaan",
        year: 2023,
        duration: 325,
        videoId: "7MERzFW3ZYU",
      },
      {
        id: "t074",
        title: "Tera Hua",
        artist: "Arijit Singh, Himesh Reshammiya",
        film: "Bad Boy",
        year: 2023,
        duration: 290,
        videoId: "_Eibm9eehFc",
      },
      {
        id: "t075",
        title: "Naya Pyaar Naya Ehsaas",
        artist: "Himesh Reshammiya",
        film: "Surroor 2021",
        year: 2021,
        duration: 310,
        videoId: "Ha3foZI-bFQ",
      },
      {
        id: "t076",
        title: "Dhaagon Se Baandhaa",
        artist: "Arijit Singh, Shreya Ghoshal, Himesh Reshammiya",
        film: "Raksha Bandhan",
        year: 2022,
        duration: 295,
        videoId: "eB127b64pnE",
      },
      {
        id: "t077",
        title: "Tuk Tuk",
        artist: "Nooran Sisters, Himesh Reshammiya",
        film: "Raksha Bandhan",
        year: 2022,
        duration: 260,
        videoId: "3WPTv59u3tA",
      },
      {
        id: "t078",
        title: "Aap Ki Kashish (Live / Alternate Versions)",
        artist: "Himesh Reshammiya",
        film: "Aashiq Banaya Aapne",
        year: 2005,
        duration: 340,
        videoId: "jx0qbW_YTCs",
      },
      {
        id: "t079",
        title: "Tera Surroor (Title Track)",
        artist: "Himesh Reshammiya",
        film: "Teraa Surroor",
        year: 2016,
        duration: 350,
        videoId: "idNyQkZU2VA",
      },
    ],
  },
  {
    id: "party-dance",
    name: "Party / Dance / High-Energy",
    tracks: [
      {
        id: "t080",
        title: "Hookah Bar",
        artist: "Himesh Reshammiya, Vineet Singh, Aman Trikha",
        film: "Khiladi 786",
        year: 2012,
        duration: 254,
        videoId: "59mHbOOYY0E",
      },
      {
        id: "t081",
        title: "Tandoori Nights",
        artist: "Himesh Reshammiya, Sunidhi Chauhan",
        film: "Karzzzz",
        year: 2008,
        duration: 280,
        videoId: "miAwePWyV78",
      },
      {
        id: "t082",
        title: "Go Go Govinda",
        artist: "Mika Singh, Shreya Ghoshal, Himesh Reshammiya",
        film: "OMG – Oh My God!",
        year: 2012,
        duration: 304,
        videoId: "H9ySOP8PYEI",
      },
      {
        id: "t083",
        title: "Jhatka Maare",
        artist: "Himesh Reshammiya",
        film: "Kyon Ki",
        year: 2005,
        duration: 270,
        videoId: "deGdp_aBOvE",
      },
      {
        id: "t084",
        title: "Just Chill",
        artist: "Sonu Nigam, Jayesh Gandhi, Amrita Kak, Himesh Reshammiya",
        film: "Maine Pyaar Kyun Kiya?",
        year: 2005,
        duration: 325,
        videoId: "w5iA5LIwF2A",
      },
      {
        id: "t085",
        title: "Maar Jawan Mit Jawan",
        artist: "Himesh Reshammiya, Sunidhi Chauhan",
        film: "Aashiq Banaya Aapne",
        year: 2005,
        duration: 290,
        videoId: "XpSicjw4v_U",
      },
      {
        id: "t086",
        title: "Bhangra Paale",
        artist: "Sadhana Sargam, Mohd. Aziz, Himesh Reshammiya",
        film: "Karan Arjun",
        year: 1995,
        duration: 340,
        videoId: "gRlAdFGZyk8",
      },
      {
        id: "t087",
        title: "Dilli Ki Sardi",
        artist: "Shweta Shetty, K.K., Himesh Reshammiya",
        film: "Zameen",
        year: 2003,
        duration: 310,
        videoId: "s8nLCS5ZnvQ",
      },
      {
        id: "t088",
        title: "Dil Dil Nazar",
        artist: "Himesh Reshammiya",
        film: "Maine Pyaar Kyun Kiya?",
        year: 2005,
        duration: 295,
        videoId: "UuLNftlHk8k",
      },
      {
        id: "t089",
        title: "No Way! No Way!",
        artist: "Himesh Reshammiya, Sunidhi Chauhan",
        film: "Anthony Kaun Hai?",
        year: 2006,
        duration: 280,
        videoId: "K3UqtrRpWJ4",
      },
      {
        id: "t090",
        title: "Let's Rock",
        artist: "Sunidhi Chauhan, Himesh Reshammiya",
        film: "Bhagam Bhag",
        year: 2006,
        duration: 275,
        videoId: "b3W6Xr5XZtQ",
      },
      {
        id: "t091",
        title: "Junoon",
        artist: "Himesh Reshammiya, Amrita Kak",
        film: "Rocky: The Rebel",
        year: 2006,
        duration: 310,
        videoId: "3I79DyDKyxI",
      },
      {
        id: "t092",
        title: "Pyar Ki Chatni",
        artist: "Sunidhi Chauhan, Himesh Reshammiya",
        film: "Phirr",
        year: 2011,
        duration: 265,
        videoId: "FHsT2h9ac7s",
      },
      {
        id: "t093",
        title: "Ghoomar",
        artist: "Shreya Ghoshal, Swaroop Khan, Himesh Reshammiya",
        film: "Padmaavat",
        year: 2018,
        duration: 282,
        videoId: "CU1tFtk_NFY",
      },
      {
        id: "t094",
        title: "Rabba Luck Barsa",
        artist: "Himesh Reshammiya",
        film: "Kajraare",
        year: 2010,
        duration: 290,
        videoId: "4ns2w4UMDls",
      },
      {
        id: "t095",
        title: "Hari Om Hari Om",
        artist: "Himesh Reshammiya",
        film: "Karzzzz",
        year: 2008,
        duration: 315,
        videoId: "mQ1iIFuaOR8",
      },
    ],
  },
  {
    id: "romantic-nostalgia",
    name: "Romantic / Love / Nostalgia",
    tracks: [
      {
        id: "t096",
        title: "Afsana Banke Bhool Na Jaana",
        artist: "Udit Narayan, Alka Yagnik, Himesh Reshammiya",
        film: "Dil Pardesi Ho Gaya",
        year: 2003,
        duration: 320,
        videoId: "psaBpso9BG4",
      },
      {
        id: "t097",
        title: "Sajan Tumse Pyar",
        artist: "Udit Narayan, Alka Yagnik, Himesh Reshammiya",
        film: "Maine Pyaar Kyun Kiya?",
        year: 2005,
        duration: 285,
        videoId: "jSkBtDg-8lg",
      },
      {
        id: "t098",
        title: "Maine Chun Liya",
        artist: "Udit Narayan, Alka Yagnik, Himesh Reshammiya",
        film: "Dil Maange More",
        year: 2004,
        duration: 310,
        videoId: "pKGiJ8f0w6Q",
      },
      {
        id: "t099",
        title: "Vaada Hai Ye",
        artist: "Udit Narayan, Alka Yagnik, Himesh Reshammiya",
        film: "Vaada",
        year: 2005,
        duration: 330,
        videoId: "OPyt4Nc6x1I",
      },
      {
        id: "t100",
        title: "Main Ishq Uska",
        artist: "Babul Supriyo, Alka Yagnik, Himesh Reshammiya",
        film: "Vaada",
        year: 2005,
        duration: 305,
        videoId: "4Y9RzwXKEWM",
      },
      {
        id: "t101",
        title: "Rabba Mere Rabba",
        artist: "Udit Narayan, Alka Yagnik, Himesh Reshammiya",
        film: "Mujhse Shaadi Karogi",
        year: 2004,
        duration: 315,
        videoId: "D4G1jVr-b6g",
      },
      {
        id: "t102",
        title: "Tune Di Bekrari",
        artist: "Shaan, Shreya Ghoshal, Himesh Reshammiya",
        film: "Aap Kaa Surroor",
        year: 2007,
        duration: 295,
        videoId: "GA3E7t5RLTE",
      },
      {
        id: "t103",
        title: "Kaun Kehta Hai",
        artist: "Udit Narayan, Shreya Ghoshal, Himesh Reshammiya",
        film: "Aap Kaa Surroor",
        year: 2007,
        duration: 310,
        videoId: "GA3E7t5RLTE",
      },
      {
        id: "t104",
        title: "Akhiyan Lada Jaa",
        artist: "Himesh Reshammiya, Sunidhi Chauhan",
        film: "Aitraaz",
        year: 2004,
        duration: 325,
        videoId: "4SpyNNc1qcc",
      },
      {
        id: "t105",
        title: "Deewanapan Deewangi",
        artist: "Sonu Nigam, Sunidhi Chauhan, Himesh Reshammiya",
        film: "Main Aisa Hi Hoon",
        year: 2005,
        duration: 300,
        videoId: "XnHJ2ifiAn0",
      },
      {
        id: "t106",
        title: "Meri Aankhon Mein",
        artist: "Udit Narayan, Alka Yagnik, Himesh Reshammiya",
        film: "Yakeen",
        year: 2005,
        duration: 290,
        videoId: "5OEOk0qmyrM",
      },
      {
        id: "t107",
        title: "Chehra Tera",
        artist: "Alka Yagnik, Sonu Nigam, Himesh Reshammiya",
        film: "Daag: The Fire",
        year: 1999,
        duration: 310,
        videoId: "ZQ6agB6s644",
      },
      {
        id: "t108",
        title: "Dil De Diya",
        artist: "Sunidhi Chauhan, Himesh Reshammiya",
        film: "Phir Hera Pheri",
        year: 2006,
        duration: 280,
        videoId: "0TKcqRMegjU",
      },
      {
        id: "t109",
        title: "Dil Ke Badle Sanam",
        artist: "Udit Narayan, Alka Yagnik, Himesh Reshammiya",
        film: "Kyon Ki",
        year: 2005,
        duration: 310,
        videoId: "fvwyPGBOEgY",
      },
      {
        id: "t110",
        title: "Tum Par Hum Hai Atke Yaara",
        artist: "Kavita Krishnamurthy, Kumar Sanu, Himesh Reshammiya",
        film: "Pyaar Kiya To Darna Kya",
        year: 1998,
        duration: 312,
        videoId: "i9qTRW89KHU",
      },
    ],
  },
];
